name: Code Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
      - run: deno test --unstable -A --coverage=coverage test/deno_runner.ts
      - run: deno coverage coverage --lcov > coverage/coverage.lcov
      - run: ./codecov -f coverage/coverage.lcov
        env:
          CODECOV_TOKEN: b878160f-a51b-491e-8499-65b91ddfdc09
