name: Test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_windows_node:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  test_macos_node:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  test_ubuntu_node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
        env:
          CI: true

  test_ubuntu_deno:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: justjavac/deno-ci
      - run: deno test -A --unstable test/deno/

  test_macos_deno:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: justjavac/deno-ci
      - run: deno test -A --unstable test/deno/

  test_windows_deno:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: justjavac/deno-ci
      - run: deno test -A --unstable test/deno/
